# Generated by Django 4.2.16 on 2024-10-11 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C')], max_length=255, null=True, verbose_name='Lokasi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipe', models.CharField(blank=True, choices=[('Meeting Room Kecil', 'Meeting Room Kecil'), ('Meeting Room Besar', 'Meeting Room Besar'), ('Aula', 'Aula')], max_length=255, null=True, verbose_name='Tipe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Ruangan')),
                ('image', models.FileField(null=True, upload_to='pattren', verbose_name='Image')),
                ('kapasitas', models.IntegerField(blank=True, null=True, verbose_name='Kapasitas')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lokasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.lokasi')),
                ('tipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PemesananRuangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nomor_pemesanan', models.CharField(max_length=255, unique=True, verbose_name='Nomor Pemesanan')),
                ('nama_pemesanan', models.CharField(max_length=255, verbose_name='Nama Pemesanan')),
                ('tanggal_pemesanan', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Pemesanan')),
                ('status_pemesanan', models.CharField(choices=[('Draft', 'Draft'), ('On Going', 'On Going'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Draft', max_length=50, verbose_name='Status Pemesanan')),
                ('catatan_pemesanan', models.TextField(blank=True, null=True, verbose_name='Catatan Pemesanan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ruangan', verbose_name='Ruangan')),
            ],
            options={
                'verbose_name': 'Pemesanan Ruangan',
                'verbose_name_plural': 'Pemesanan Ruangan',
                'ordering': ['-tanggal_pemesanan'],
            },
        ),
    ]
