# Generated by Django 4.2.16 on 2024-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='image',
            field=models.FileField(null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
